/* mockData.js – Fallback data when Sanity API is unavailable */

const MOCK_POSTS = [
  {
    _id: '1',
    title: 'Türkiye\'nin Altın Madenciliğinde Yeni Dönem',
    slug: { current: 'turkiyenin-altin-madenciliginde-yeni-donem' },
    excerpt: 'Türkiye altın madenciliğinde önemli adımlar atarak dünya sıralamasında yükselmeye devam ediyor. Yeni keşfedilen rezervler sektörün geleceğini şekillendiriyor.',
    category: 'news',
    tags: ['altın', 'türkiye', 'madencilik'],
    coverImageUrl: 'https://images.unsplash.com/photo-1605792657660-596af9009e82?w=800&h=450&fit=crop',
    publishedAt: '2026-02-28',
    featured: true,
    body: [
      { _type: 'block', style: 'normal', children: [{ _type: 'span', text: 'Türkiye, son yıllarda altın madenciliği alanında büyük bir atılım gerçekleştirdi. Yeni keşfedilen rezervler ve artan yatırımlar sayesinde ülke, dünya altın üretiminde önemli bir konuma yükseldi.' }] },
      { _type: 'block', style: 'h2', children: [{ _type: 'span', text: 'Yeni Rezerv Keşifleri' }] },
      { _type: 'block', style: 'normal', children: [{ _type: 'span', text: 'Erzincan, Gümüşhane ve Artvin bölgelerinde yapılan araştırmalar sonucunda yeni altın yatakları tespit edildi. Bu keşifler, Türkiye\'nin altın rezervlerini önemli ölçüde artırdı.' }] },
      { _type: 'block', style: 'normal', children: [{ _type: 'span', text: 'Uzmanlar, bu gelişmelerin Türkiye\'yi önümüzdeki 10 yıl içinde dünya altın üretiminde ilk 10\'a taşıyabileceğini öngörüyor.', marks: ['em'] }] },
    ],
  },
  {
    _id: '2',
    title: 'Güney Afrika\'da Madenci Hayatı: Derinlerin Hikayeleri',
    slug: { current: 'guney-afrikada-madenci-hayati' },
    excerpt: 'Güney Afrika\'nın derin madenlerde çalışan insanların günlük yaşamlarına yakından bakıyoruz. Yerin 3 km altındaki hayat nasıl?',
    category: 'story',
    tags: ['güney afrika', 'madenci hayatı', 'derinlik'],
    coverImageUrl: 'https://images.unsplash.com/photo-1578328819058-b69f3a3680e5?w=800&h=450&fit=crop',
    publishedAt: '2026-02-25',
    featured: false,
    body: [
      { _type: 'block', style: 'normal', children: [{ _type: 'span', text: 'Güney Afrika, dünyanın en derin madenlerine ev sahipliği yapıyor. Bu madenlerde çalışan binlerce işçi, her gün yerin kilometrelerce altına inerek zorlu koşullarda çalışıyor.' }] },
    ],
  },
  {
    _id: '3',
    title: 'Prof. Dr. Ayşe Demir ile Sürdürülebilir Madencilik Üzerine',
    slug: { current: 'prof-dr-ayse-demir-surdurulebilir-madencilik' },
    excerpt: 'İstanbul Teknik Üniversitesi Maden Fakültesi öğretim üyesi Prof. Dr. Ayşe Demir ile sürdürülebilir madencilik uygulamalarını konuştuk.',
    category: 'interview',
    tags: ['röportaj', 'sürdürülebilirlik', 'akademi'],
    coverImageUrl: 'https://images.unsplash.com/photo-1551836022-4c4c79ecde51?w=800&h=450&fit=crop',
    publishedAt: '2026-02-22',
    featured: false,
    body: [
      { _type: 'block', style: 'normal', children: [{ _type: 'span', text: 'Sürdürülebilir madencilik, sektörün en önemli gündem maddelerinden biri haline geldi. Prof. Dr. Ayşe Demir ile bu konudaki son gelişmeleri değerlendirdik.' }] },
    ],
  },
  {
    _id: '4',
    title: 'Lityum Savaşları: Geleceğin Madeninin Peşinde',
    slug: { current: 'lityum-savaslari-gelecegin-madeninin-pesinde' },
    excerpt: 'Elektrikli araçların yükselişi ile birlikte lityum talebi patlama yaşıyor. Güney Amerika\'nın "lityum üçgeni" neden bu kadar önemli?',
    category: 'story',
    tags: ['lityum', 'elektrikli araçlar', 'güney amerika'],
    coverImageUrl: 'https://images.unsplash.com/photo-1558618666-fcd25c85f82e?w=800&h=450&fit=crop',
    publishedAt: '2026-02-18',
    featured: false,
    body: [
      { _type: 'block', style: 'normal', children: [{ _type: 'span', text: 'Lityum, modern teknoloji için vazgeçilmez bir element. Bolivya, Şili ve Arjantin üçgeninde bulunan devasa lityum rezervleri, küresel güç dengelerini yeniden şekillendiriyor.' }] },
    ],
  },
  {
    _id: '5',
    title: 'Madencilik Sektöründe Dijital Dönüşüm',
    slug: { current: 'madencilik-sektorunde-dijital-donusum' },
    excerpt: 'Yapay zeka, IoT sensörler ve otonom araçlar madencilik sektörünü köklü bir şekilde değiştiriyor. İşte dijital dönüşümün yol haritası.',
    category: 'news',
    tags: ['dijital dönüşüm', 'yapay zeka', 'teknoloji'],
    coverImageUrl: 'https://images.unsplash.com/photo-1518770660439-4636190af475?w=800&h=450&fit=crop',
    publishedAt: '2026-02-15',
    featured: false,
    body: [
      { _type: 'block', style: 'normal', children: [{ _type: 'span', text: 'Dijital dönüşüm, madencilik sektörünü de etkisi altına aldı. Yapay zeka destekli analiz sistemleri, IoT sensörler ve otonom araçlar, madenciliğin geleceğini şekillendiriyor.' }] },
    ],
  },
  {
    _id: '6',
    title: 'Avustralya Demir Madenleri: Pilbara Bölgesi',
    slug: { current: 'avustralya-demir-madenleri-pilbara' },
    excerpt: 'Dünyanın en büyük demir cevheri ihracatçısı Avustralya\'nın Pilbara bölgesini ve buradaki devasa madencilik operasyonlarını keşfediyoruz.',
    category: 'story',
    tags: ['avustralya', 'demir', 'pilbara'],
    coverImageUrl: 'https://images.unsplash.com/photo-1570723279293-27413c7ca922?w=800&h=450&fit=crop',
    publishedAt: '2026-02-12',
    featured: false,
    body: [
      { _type: 'block', style: 'normal', children: [{ _type: 'span', text: 'Avustralya\'nın batısındaki Pilbara bölgesi, dünyanın en büyük demir cevheri yataklarına ev sahipliği yapıyor.' }] },
    ],
  },
  {
    _id: '7',
    title: 'Sektör Güncesi: Mart 2026 Madencilik Haberleri',
    slug: { current: 'sektor-guncesi-mart-2026' },
    excerpt: 'Bu ayki sektör özetimizde bakır fiyatlarındaki yükseliş, yeni maden ruhsatları ve çevre düzenlemelerindeki değişiklikleri ele alıyoruz.',
    category: 'update',
    tags: ['güncel', 'bakır', 'sektör'],
    coverImageUrl: 'https://images.unsplash.com/photo-1504328345606-18bbc8c9d7d1?w=800&h=450&fit=crop',
    publishedAt: '2026-03-01',
    featured: false,
    body: [
      { _type: 'block', style: 'normal', children: [{ _type: 'span', text: 'Mart 2026 madencilik sektörü için hareketli bir ay oldu. İşte öne çıkan gelişmeler.' }] },
    ],
  },
  {
    _id: '8',
    title: 'Maden Mühendisi Ahmet Yılmaz ile Sahadan',
    slug: { current: 'maden-muhendisi-ahmet-yilmaz-ile-sahadan' },
    excerpt: '15 yıllık saha deneyimine sahip maden mühendisi Ahmet Yılmaz, madencilikte güvenlik kültürünü ve saha gerçeklerini anlatıyor.',
    category: 'interview',
    tags: ['röportaj', 'maden mühendisi', 'güvenlik'],
    coverImageUrl: 'https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=800&h=450&fit=crop',
    publishedAt: '2026-02-08',
    featured: false,
    body: [
      { _type: 'block', style: 'normal', children: [{ _type: 'span', text: 'Ahmet Yılmaz, 15 yıldır sahada çalışan deneyimli bir maden mühendisi. Kendisiyle madencilikte güvenlik kültürü ve saha gerçekleri üzerine kapsamlı bir sohbet gerçekleştirdik.' }] },
    ],
  },
  {
    _id: '9',
    title: 'Nadir Toprak Elementleri ve Küresel Rekabet',
    slug: { current: 'nadir-toprak-elementleri-kuresel-rekabet' },
    excerpt: 'Teknoloji dünyasının olmazsa olmaz hammaddeleri nadir toprak elementleri üzerine bir analiz. Çin\'in hakimiyeti kırılabilir mi?',
    category: 'news',
    tags: ['nadir toprak', 'çin', 'küresel rekabet'],
    coverImageUrl: 'https://images.unsplash.com/photo-1611284446314-60a58ac0deb9?w=800&h=450&fit=crop',
    publishedAt: '2026-02-05',
    featured: false,
    body: [
      { _type: 'block', style: 'normal', children: [{ _type: 'span', text: 'Nadir toprak elementleri, modern teknolojinin temel yapı taşlarından biridir. Akıllı telefonlardan elektrikli araçlara, rüzgar türbinlerinden savunma sistemlerine kadar pek çok alanda kullanılmaktadır.' }] },
    ],
  },
];

const MOCK_VIDEOS = [
  {
    _id: 'v1',
    title: 'Dünyanın En Derin Madeni: Mponeng',
    slug: { current: 'dunyanin-en-derin-madeni-mponeng' },
    coverImageUrl: 'https://images.unsplash.com/photo-1578328819058-b69f3a3680e5?w=800&h=450&fit=crop',
    youtubeEmbed: '<iframe width="560" height="315" src="https://www.youtube.com/embed/dQw4w9WgXcQ" title="Mponeng" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',
    publishedAt: '2026-02-20',
    featured: true,
  },
  {
    _id: 'v2',
    title: 'Altın Nasıl İşlenir? Rafineride Bir Gün',
    slug: { current: 'altin-nasil-islenir-rafineride-bir-gun' },
    coverImageUrl: 'https://images.unsplash.com/photo-1605792657660-596af9009e82?w=800&h=450&fit=crop',
    youtubeEmbed: '<iframe width="560" height="315" src="https://www.youtube.com/embed/dQw4w9WgXcQ" title="Altın Rafinerisi" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',
    publishedAt: '2026-02-15',
    featured: false,
  },
  {
    _id: 'v3',
    title: 'Madencilik ve Çevre: Denge Mümkün mü?',
    slug: { current: 'madencilik-ve-cevre-denge-mumkun-mu' },
    coverImageUrl: 'https://images.unsplash.com/photo-1551836022-4c4c79ecde51?w=800&h=450&fit=crop',
    youtubeEmbed: '<iframe width="560" height="315" src="https://www.youtube.com/embed/dQw4w9WgXcQ" title="Madencilik ve Çevre" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',
    publishedAt: '2026-02-10',
    featured: false,
  },
  {
    _id: 'v4',
    title: 'Otonom Kamyonlar: Madenciliğin Geleceği',
    slug: { current: 'otonom-kamyonlar-madenciligin-gelecegi' },
    coverImageUrl: 'https://images.unsplash.com/photo-1518770660439-4636190af475?w=800&h=450&fit=crop',
    youtubeEmbed: '<iframe width="560" height="315" src="https://www.youtube.com/embed/dQw4w9WgXcQ" title="Otonom Kamyonlar" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',
    publishedAt: '2026-02-05',
    featured: false,
  },
  {
    _id: 'v5',
    title: 'Kömür Madenciliğinin Tarihçesi',
    slug: { current: 'komur-madenciliginin-tarihcesi' },
    coverImageUrl: 'https://images.unsplash.com/photo-1504328345606-18bbc8c9d7d1?w=800&h=450&fit=crop',
    youtubeEmbed: '<iframe width="560" height="315" src="https://www.youtube.com/embed/dQw4w9WgXcQ" title="Kömür Madenciliği" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',
    publishedAt: '2026-01-30',
    featured: false,
  },
  {
    _id: 'v6',
    title: 'Türkiye Bor Madenciliği Belgeseli',
    slug: { current: 'turkiye-bor-madenciligi-belgeseli' },
    coverImageUrl: 'https://images.unsplash.com/photo-1570723279293-27413c7ca922?w=800&h=450&fit=crop',
    youtubeEmbed: '<iframe width="560" height="315" src="https://www.youtube.com/embed/dQw4w9WgXcQ" title="Bor Madenciliği" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',
    publishedAt: '2026-01-25',
    featured: false,
  },
];
